# Generated by Django 5.2 on 2025-07-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='user_update',
        ),
    ]
